#@ load("@ytt:data", "data")
#@ load("common.lib.yaml", "getVersionByPackage")
---
apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageRepository
metadata:
  name: tanzu-standard
  namespace: package-repo
spec:
  fetch:
    imgpkgBundle:
      image: #@ "{}/packages/standard:{}".format(data.values.image_registry,getVersionByPackage("standard-repo"))
      secretRef:
        name: #@ data.values.credentials_secret
