apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageRepository
metadata:
  name: tanzu-standard
  namespace: package-repo
spec:
  fetch:
    imgpkgBundle:
      image: harbor.build.h2o-2-18171.h2o.vmware.com/packages/standard:v2023.7.13_update.2