apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageRepository
metadata:
  name: tanzu-standard
  namespace: package-repo
spec:
  fetch:
    imgpkgBundle:
      image: #@ data.values.registry_credentials+"/packages/standard:v2023.7.13_update.2"
      secretRef:
        name: harbor-registry-creds