---
apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
  name: fluentbit
  namespace: package-repo
spec:
  packageRef:
    refName: fluent-bit.tanzu.vmware.com
    versionSelection:
      constraints: 2.1.2+vmware.1-tkg.1 
  values:
  - secretRef:
      name: fluentbit-values
  serviceAccountName: kapp-gitops-sa
---
apiVersion: v1
kind: Secret
metadata:
  name: fluentbit-values
  namespace: package-repo
stringData:
  values.yml: |
    ---
    fluent_bit:
      config:
        outputs: |
          [OUTPUT]
            Name                 syslog
            Match                *
            Host                 192.168.100.10
            Port                 514
            Mode                 tcp
            Syslog_Format        rfc5424
            Syslog_Hostname_key  tkg_cluster
            Syslog_Appname_key   pod_name
            Syslog_Procid_key    container_name
            Syslog_SD_key        annotations
            Syslog_SD_key        labels
            Syslog_SD_key        k8s
            Syslog_SD_key        tkg
            Syslog_Message_key   message
