---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    kubernetes.io/metadata.name: package-repo
  name: package-repo
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kapp-gitops-sa
  namespace: package-repo
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kapp-gitops-sa
  namespace: tkg-system
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: default-ns-role
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: default-ns-role-binding
subjects:
- kind: ServiceAccount
  name: kapp-gitops-sa
  namespace: package-repo
- kind: ServiceAccount
  name: kapp-gitops-sa
  namespace: tkg-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: default-ns-role
---
apiVersion: v1
kind: Secret
metadata:
  name: cluster-data
  namespace: tkg-system
  annotations:
type: generic
data:
  data.yaml: |
    name: ""
    harbor_namespace: ""
    gitops_repo: ""
    gitops_ref: ""
    packages: []

