apiVersion: kappctrl.k14s.io/v1alpha1
kind: App
metadata:
  name: shared-services
  namespace: tkg-system
spec:
  serviceAccountName: default-ns-sa
  fetch:
  - git:
      url: https://github.com/tsfrt/gitops-example
      ref: origin/main
  template:
  - sops:
      age:
        privateKeysSecretRef:
          name: enc-key
  - ytt:
      ignoreUnknownComments: true
      paths:
      - common
      - cert-manager
      - contour
      - harbor/app
  deploy:
  - kapp: {}