apiVersion: kappctrl.k14s.io/v1alpha1
kind: App
metadata:
  name: shared-services
  namespace: tkg-system
spec:
  serviceAccountName: kapp-gitops-sa  
  fetch:
  - git:
      url: https://github.com/tsfrt/gitops-example
      ref: origin/main
  template:
  - sops:
      age:
        privateKeysSecretRef:
          name: enc-key
  - ytt:
      ignoreUnknownComments: true
      paths:
      - common
      - cluster-config/shared-services
      - standard-repo
      - cert-manager
      - contour
      - harbor/app
      - fluentbit
      - enterprise-routing
  deploy:
  - kapp: {}
