---
apiVersion: templates.gatekeeper.sh/v1beta1
kind: ConstraintTemplate
metadata:
  name: denyrestrictednamespaceaccess
  namespace: gatekeeper
  annotations:
    kapp.k14s.io/change-group: "policy"
spec:
  crd:
    spec:
      names:
        kind: DenyRestrictedNamespaceAccess
  targets:
    - target: admission.k8s.gatekeeper.sh
      rego: |
        package DenyNamespace

        violation[{"msg": msg}] {
          not contains(input.review.userInfo.group, "developers")
          msg := sprintf("you cant use namespace: %v", [input.review.object.metadata.namespace])
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: denyrestrictednamespaceaccess.constraints.gatekeeper.sh
  annotations:
    kapp.k14s.io/exists: ""
    kapp.k14s.io/change-group: "policy"
spec:
  group: constraints.gatekeeper.sh
  versions:
    - name: v1beta1
  names:
    kind: denyrestrictednamespaceaccess
---
apiVersion: constraints.gatekeeper.sh/v1beta1
kind: DenyRestrictedNamespaceAccess
metadata:
  name: denyrestrictednamespaceaccess
  namespace: gatekeeper
  annotations:
    kapp.k14s.io/change-rule: "upsert after upserting policy"
spec:
  match:
    namespaces:
      - kube-system
      - package-repo