#@ load("@ytt:data", "data")
---
apiVersion: kappctrl.k14s.io/v1alpha1
kind: App
metadata:
  name: enterprise-routing
  namespace: package-repo
spec:
  fetch:
  - git:
      ref: origin/main
      subPath: enterprise-routing
      url: https://github.com/tsfrt/ingress-example
  serviceAccountName: #@ data.values.service_account_name
  template:
  - sops:
      age:
        privateKeysSecretRef:
          name: enc-key
  - ytt:
     paths:
        - "."
  - kbld: {}
  deploy:
  - kapp: {}
      