#@ load("@ytt:data", "data")
#@ load("common.lib.yaml", "getVersionByPackage", "getValuesByPackage")
---
apiVersion: secretgen.carvel.dev/v1alpha1
kind: SecretImport
metadata:
  name: git-creds
  namespace: #@ data.values.harbor_namespace
  annotations:
    kapp.k14s.io/change-rule: "upsert after upserting root-cluster-secrets"
    kapp.k14s.io/change-group: "cluster-secrets"
spec:
  fromNamespace: tkg-system
---
apiVersion: v1
kind: Secret
metadata:
  name: #@ data.values.credentials_secret
  namespace: #@ data.values.harbor_namespace
  annotations:
    secretgen.carvel.dev/image-pull-secret: ""
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: "e30K"
---
apiVersion: kappctrl.k14s.io/v1alpha1
kind: App
metadata:
  name: harbor-helm
  namespace: package-repo
spec:
  deploy:
  - kapp:
      intoNs: #@ data.values.harbor_namespace
  fetch:
  - helmChart:
      name: harbor
      repository:
        url: oci://harbor.build.h2o-2-18171.h2o.vmware.com/charts
        secretRef:
            name: #@ data.values.credentials_secret
      version: #@ getVersionByPackage("harbor/app")
  - git:
      ref: origin/main
      subPath: harbor/harbor-artifacts
      url: https://github.com/tsfrt/gitops-example
      secretRef:
        name: git-creds
  serviceAccountName: #@ data.values.service_account_name
  template:
  - sops:
      age:
        privateKeysSecretRef:
          name: enc-key
  - helmTemplate:
      path: 0/
      valuesFrom:
      - secretRef:
          name: #@ getValuesByPackage("harbor/app")
  - ytt:
      inline:
        pathsFrom:
        - secretRef:
            name: common-lib
  - kbld:
      paths:
      - 1/harbor.lock.copied
      - '-'