#@ load("@ytt:data", "data")
---
apiVersion: kappctrl.k14s.io/v1alpha1
kind: App
metadata:
  name: harbor-helm
  namespace: package-repo
spec:
  deploy:
  - kapp:
      intoNs: #@ data.values.harbor_namespace
  fetch:
  - helmChart:
      name: harbor
      repository:
        url: oci://harbor.build.h2o-2-18171.h2o.vmware.com/charts
        secretRef:
            name: harbor-registry-creds
      version: 1.13.0
  - git:
      ref: origin/main
      subPath: harbor/harbor-artifacts
      url: https://github.com/tsfrt/gitops-example
  serviceAccountName: kapp-gitops-sa  
  template:
  - sops:
      age:
        privateKeysSecretRef:
          name: enc-key
  - helmTemplate:
      path: 0/
      valuesFrom:
      - secretRef:
          name: harbor-values
  - ytt:
      inline:
        pathsFrom:
        - secretRef:
            name: image-pull-overlay
  - kbld:
      paths:
      - 1/harbor.lock.copied
      - '-'