#@ load("@ytt:data", "data")
#@ load("common.lib.yaml", "getVersionByPackage", "getValuesByPackage")
---
apiVersion: kappctrl.k14s.io/v1alpha1
kind: App
metadata:
  name: harbor-helm
  namespace: package-repo
spec:
  deploy:
  - kapp:
      intoNs: #@ data.values.harbor_namespace
  fetch:
  - helmChart:
      name: harbor
      repository:
        url: oci://harbor.build.h2o-2-18171.h2o.vmware.com/charts
        secretRef:
            name: #@ data.values.credentials_secret
      version: #@ getVersionByPackage("harbor/app")
  - git:
      ref: origin/main
      subPath: harbor/harbor-artifacts
      url: https://github.com/tsfrt/gitops-example
  serviceAccountName: #@ data.values.service_account_name
  template:
  - sops:
      age:
        privateKeysSecretRef:
          name: enc-key
  - helmTemplate:
      path: 0/
      valuesFrom:
      - secretRef:
          name: #@ getValuesByPackage("harbor/app")
  - ytt:
      inline:
        pathsFrom:
        - secretRef:
            name: common-lib
  - kbld:
      paths:
      - 1/harbor.lock.copied
      - '-'