#@ load("@ytt:data", "data")
---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    pod-security.kubernetes.io/enforce: privileged
    kubernetes.io/metadata.name: #@ data.values.harbor_namespace
  name: #@ data.values.harbor_namespace