{
 "title": "kapp-controller",
 "description": "kapp-controller metrics and overview for installed PackageRepository, PackageInstall and App.",
 "tags": [
  "observability",
  "kapp-controller",
  "kapp"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "cluster",
    "query": {
     "query": "label_values(agent_build_info,cluster)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview / Count", "type": "text", "gridPos": { "h": 1, "w": 12, "x": 0, "y": 0 } },
  { "title": "Not Succeeded (yet)", "type": "text", "gridPos": { "h": 1, "w": 6, "x": 12, "y": 0 } },
  {
   "title": "Status not set (failed or unknown)",
   "type": "text",
   "gridPos": { "h": 1, "w": 6, "x": 18, "y": 0 }
  },
  {
   "title": "PackageRepositories",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kapp_packagerepository_info{cluster=~\"$cluster\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "PackageInstalls",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kapp_packageinstall_info{cluster=~\"$cluster\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Apps",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kapp_app_info{cluster=~\"$cluster\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "PackageRepositories",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kapp_packagerepository_info{cluster=~\"$cluster\", status=\"True\", type!=\"ReconcileSucceeded\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "PackageInstalls",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kapp_packageinstall_info{cluster=~\"$cluster\", status=\"True\", type!=\"ReconcileSucceeded\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Apps",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kapp_app_info{cluster=~\"$cluster\", status=\"True\", type!=\"ReconcileSucceeded\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "PackageRepositories",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kapp_packagerepository_info{cluster=~\"$cluster\", status!=\"True\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "PackageInstalls",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kapp_packageinstall_info{cluster=~\"$cluster\", status!=\"True\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Apps",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kapp_app_info{cluster=~\"$cluster\", status!=\"True\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "PackageRepository / Current state",
   "type": "table",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 4 },
   "targets": [
    {
     "expr": "sum(kapp_packagerepository_info{cluster=~\"$cluster\"}) by (name, namespace, oci_image, git_url, git_ref, type, status)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "PackageRepository / State over time",
   "type": "state-timeline",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 4 },
   "targets": [
    {
     "expr": "sum(kapp_packagerepository_info{cluster=~\"$cluster\"}) by (name, namespace, type, status, package_name, package_version)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "PackageInstall / Current state",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum(kapp_packageinstall_info{cluster=~\"$cluster\"}) by (name, namespace, package_name, package_version, type, status)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "PackageInstall / State over time",
   "type": "state-timeline",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "sum(kapp_packageinstall_info{cluster=~\"$cluster\"}) by (name, namespace, type, status, package_name, package_version)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "App / Current state",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "sum(kapp_app_info{cluster=~\"$cluster\"}) by (name, namespace, oci_image, git_url, git_ref, type, status)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "App / State over time",
   "type": "state-timeline",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "sum(kapp_app_info{cluster=~\"$cluster\"}) by (name, namespace, type, status, package_name, package_version)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "PackageInstall / Version over time",
   "type": "state-timeline",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 28 },
   "targets": [
    {
     "expr": "sum(kapp_packageinstall_info{cluster=~\"$cluster\"}) by (name, namespace, type, status, package_name, package_version)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}