#@ load("@ytt:data", "data")
#@ load("common.lib.yaml", "getVersionByPackage", "getValuesByPackage")

---
apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
  name: contour
  namespace: package-repo
spec:
  packageRef:
    refName: contour.tanzu.vmware.com
    versionSelection:
      constraints: #@ getVersionByPackage("contour")
  serviceAccountName: #@ data.values.service_account_name
  values:
   - secretRef:
      name:  getValuesByPackage("contour")
---
apiVersion: v1
kind: Secret
metadata:
  name: contour-default-values
  namespace: package-repo
stringData:
  #@yaml/text-templated-strings
  values.yml: |
    contour:
      configFileContents:
        enableExternalNameService: (@= data.values.countour_external_name @)
    envoy:
     service:
       type: LoadBalancer
       loadBalancerIP: (@= data.values.ingress_ip @)
   
       