#@ load("@ytt:data", "data")
---
apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
  name: contour
  namespace: package-repo
spec:
  packageRef:
    refName: contour.tanzu.vmware.com
    versionSelection:
      constraints: 1.24.4+vmware.1-tkg.1
  serviceAccountName: #@ data.values.service_account_name
  values:
   - secretRef:
      name:  contour-values
---
apiVersion: v1
kind: Secret
metadata:
  name: contour-values
  namespace: package-repo
stringData:
  #@yaml/text-templated-strings
  values.yml: |
    envoy:
     service:
       type: LoadBalancer
       loadBalancerIP: (@= data.values.ingress_ip @)
       