#@ load("@ytt:data", "data")
---
apiVersion: v1
kind: Secret
data:
  data.yaml: "e30K"
metadata:
  name: cluster-data
  namespace: package-repo
  annotations:
    kapp.k14s.io/change-group: "cluster-secrets"
---
apiVersion: kappctrl.k14s.io/v1alpha1
kind: App
metadata:
  name: #@ data.values.name
  namespace: package-repo
  annotations:
    kapp.k14s.io/change-rule: "upsert after upserting cluster-secrets"
spec:
  serviceAccountName: kapp-gitops-sa
  fetch:
    - git:
        url: #@ data.values.gitops_repo
        ref: #@ data.values.gitops_ref
  template:
    - sops:
        age:
          privateKeysSecretRef:
            name: enc-key
    - ytt:
        inline:
          pathsFrom:
            - secretRef: cluster-data
        ignoreUnknownComments: true
        paths:
        #@ for/end package in data.values.packages:
        - #@ package
        valuesFrom:
          - secretRef:
              name: cluster-data
  deploy:
    - kapp: {}
