#@ load("@ytt:data", "data")
---
apiVersion: secretgen.carvel.dev/v1alpha1
kind: SecretImport
metadata:
  name: cluster-data
  namespace: package-repo
  annotations:
    kapp.k14s.io/change-rule: "upsert after upserting root-cluster-secrets"
    kapp.k14s.io/change-group: "cluster-secrets"
spec:
  fromNamespace: tkg-system
---
apiVersion: secretgen.carvel.dev/v1alpha1
kind: SecretImport
metadata:
  name: git-creds
  namespace: package-repo
  annotations:
    kapp.k14s.io/change-rule: "upsert after upserting root-cluster-secrets"
    kapp.k14s.io/change-group: "cluster-secrets"
spec:
  fromNamespace: tkg-system
---
apiVersion: kappctrl.k14s.io/v1alpha1
kind: App
metadata:
  name: #@ data.values.name+"-packages"
  namespace: package-repo
  annotations:
    kapp.k14s.io/change-rule: "upsert after upserting cluster-secrets"
spec:
  serviceAccountName: #@ data.values.service_account_name
  fetch:
    - git:
        url: #@ data.values.gitops_repo
        ref: #@ data.values.gitops_ref
        secretRef:
          name: git-creds
  template:
    - sops:
        age:
          privateKeysSecretRef:
            name: enc-key
    - ytt:
        ignoreUnknownComments: true
        inline:
          pathsFrom:
          - secretRef:
              name: common-lib
        paths:
          #@ for/end package in data.values.packages:
          -  #@ package.name
        valuesFrom:
          - secretRef:
              name: cluster-data
  deploy:
    - kapp: {}
