apiVersion: secretgen.carvel.dev/v1alpha1
kind: SecretExport
metadata:
  name: cluster-data
  namespace: tkg-system
  annotations:
    kapp.k14s.io/change-group: "cluster-secrets"
spec:
  toNamespaces:
  - "*"  