#@ load("@ytt:data", "data")
---
apiVersion: kappctrl.k14s.io/v1alpha1
kind: App
metadata:
  name: #@ data.values.name
  namespace: package-repo
  serviceAccountName: kapp-gitops-sa
spec:
  fetch:
    - git:
        url: #@ data.values.gitops_repo
        ref: #@ data.values.gitops_ref
  template:
    - sops:
        age:
          privateKeysSecretRef:
            name: enc-key
    - ytt:
        fileMarks:
        - data.yaml:exclude=true
        ignoreUnknownComments: true
        paths:
        #@ for/end package in data.values.packages:
        - #@ package
        valuesFrom:
          - secretRef:
              name: cluster-data
  deploy:
    - kapp: {}
