apiVersion: v1
data:
  overlay.yaml: #@ base64.encode(data.read("image-pull-overlay.yaml")
  common.lib.yaml: #@ base64.encode(data.read("common.lib.yaml")
kind: Secret
metadata:
  creationTimestamp: null
  name: common-lib
  namespace: package-repo
