#@ load("@ytt:data", "data")
---
apiVersion: secretgen.carvel.dev/v1alpha1
kind: SecretExport
metadata:
  name: #@ data.values.credentials_secret
  namespace: package-repo
  annotations:
    kapp.k14s.io/change-group: "cluster-secrets"
    kapp.k14s.io/change-rule: "upsert after upserting root-cluster-secrets"
spec:
  toNamespaces:
  - "*"  