#@ load("@ytt:data", "data")
---
apiVersion: secretgen.carvel.dev/v1alpha1
kind: SecretExport
metadata:
  name: #@ data.values.credentials_secret
  namespace: package-repo
spec:
  toNamespaces:
  - "*"  