apiVersion: ENC[AES256_GCM,data:dHk=,iv:UqGPS6d48qfrMsGf9TSAaodIwT/Vla9UW+lwWFh/1+s=,tag:EKzws6gvuZxc+SK2TOwd1Q==,type:str]
data:
    secret: ENC[AES256_GCM,data:0M1CnhARr/VlfDzvhyNZh23+jYWRZTVTxt+ic93gXqDnzqHM9hijRjIO8bcoXsaG16ooGOQw5OEtXs7/2iLZLFM5U75xhKh6ClWnhwWHDDRbo6uaQscGdWmoiHhtHWUhb4y9IU2mNhiCZ3D2BtJFciUu9wuEwtXPSJrXErKzmhDX/oKgo2waww==,iv:heMFr/sea4ysLYPEog7F3krsV67rH7H3mj+8bjI0EGM=,tag:jtBYQ9eyh2KQTDU206dJ6g==,type:str]
kind: ENC[AES256_GCM,data:MvqVb8GB,iv:7kXE0suxVpG7NSpJvytw25ioFUuPlHEs4Tr8AnRXf3o=,tag:NwQw5WXGrB5zcD8IDxYiCA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:OrYxjY6kbqkfxFhPNas7Bv7LtA==,iv:orWVkRFEdavEYmjHwrRlMlzbHvxDSFmi27+NlM2kP/E=,tag:xIOv2PbzbEf1UUVVA3MzCQ==,type:str]
    namespace: ENC[AES256_GCM,data:srMuBW39,iv:AMOdVYAWR1flSrSBFFK+aDjs930HjngHZBSy4UDZt00=,tag:eo1pQBMVk12L5cX5795RYg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1k0pw8ujs33xpk0sjuxex64nqhz4c4j5yhus3lka077sv868rv4qq4upsu4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKS1Vhamg4YWhkVC9CWnA2
            ckdGM2UzQXh3Ym92RXBTUmJjTkQ4UFJIeEJRCjJjUzE2b0NReklDWHV6UDBGT1dy
            YUlpK0p5MTh6RTRyb3FKUWk2bzV4WmMKLS0tIGFUUDk1MHFSOXRDMGIvbDhkWjNz
            UFpkZmJRMmRIM2xYRDBNSFZMNjZsTHcK7dbC7zypa1hNzTf/lgvrGh+5wSZBb0nq
            eQOAkrpk5NkgJSvFgQvi/p2Gt4qNOvBv7ODh9dTyPXWluz71Xsfe1A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-06T02:27:28Z"
    mac: ENC[AES256_GCM,data:Cfej/kZtsVGbUtGfh6/+/NESezwpJN5t8Pmszvj+1TNPKk+NcKMayuI3iwDmR5LHO/UjE18w1sfccQltoTdCzJQwCD1gUzYMmeYpIPiQTrGyezyn/l0g2ihaKRBnggDSuicqItARoFsFbwWgJY+p2k2djOVHexly7c2vkqhnIcM=,iv:fp3JzpF6fL+HgsCbgLwrz8fQReL7aiODpfU7tHPblHA=,tag:nOJjJ/tZ+nlAtjTTf0OucA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.0
