apiVersion: ENC[AES256_GCM,data:z4M=,iv:548YHb39r1N86wz+HAeyGywULCGvFMefHuzsjheJ6jo=,tag:z5rgDwb6A2at7kBZY7fYvg==,type:str]
data:
    secret: ENC[AES256_GCM,data:vfKmHGp+uMnpwebxZAqKAgEGylwLKkhhR6xHF/F7dVCDhDAGKa4CiI33gPI/186d4kP4IMPlzhQ7sfOMXY29/3v7kAtf+hwKDrzLxTy67SqjJerS4wsWUU899fD2R/5dTfAMmp21YQaqike9/+gmooh2dqCbTzd/FDJZhdnVVWynpzIZjwMaRw==,iv:NXVji2W99v83PKVmgUiJ2WUSAybN6r/bmeHTrUWuJ/c=,tag:5eOGWmQ1DPdzvVNb0/IZ6A==,type:str]
kind: ENC[AES256_GCM,data:pFQ4sI59,iv:oN2VSLssXqtXfiwjfxnoDh8yQxwwThb4P6DouxbfPb0=,tag:GBlqH2hwyDvvayq1lCmEIw==,type:str]
metadata:
    creationTimestamp: null
    name: ENC[AES256_GCM,data:VgtvuOAHnYaqY8GTH1YRCTOKXA==,iv:vDOJIvTXAEzeADRyKjssYgCS7N/axWoC7wTGaBgWTE4=,tag:hMSNtxWGI+8lc9y4bGkbVQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1k0pw8ujs33xpk0sjuxex64nqhz4c4j5yhus3lka077sv868rv4qq4upsu4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFLzR0cHRZZ1ZKSmRRNUIy
            S2hHQWNQNkdsdXZyVmUxR2w5endtY0EzVldFCmpZc0xXMkZhSUpKQVhjYzdTMEpC
            RnplNW8vRFV5Qk5ybUpKK2hyRjdtVjQKLS0tIDVhMEJQTCszQmJ5Vmd4eGhYWTVU
            S3pITXc5bmRiTm9oUnd6d3c5Rm9KS2MK3lBKyEMgZGgXBqdKkKQ0yx71i5esipkR
            i2637DCmAnkR21dhcnIHTxxpBBrNEwkGoOzX/C6AgGHbsbEm6YqVrQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-06T02:59:35Z"
    mac: ENC[AES256_GCM,data:DKqEMA7+kE1AnoOTjrQvtsJ2tM8VQ/bs54mjdc64e4E1TAD59fgRtR3G6K2uxB0VrRZTY9Ig/JQvi4w+Bm4NnmxzABlldXqvdKI6y2BDRuWGi6D+uG6iFl2YOkMmqOw9hqU6LDOEyP8noa3c+H7DoToBYBx3CV3IEfwPGAepzvY=,iv:Yja+iofPoA9mK4xiCPNrzu2GAqrlGqQfppEhOs6elsI=,tag:bdYFIvVKP142g57DJMwfVg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.0
