#@ load("@ytt:data", "data")
#@ load("common.lib.yaml", "getVersionByPackage")
---
apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
  name: cert-manager
  namespace: package-repo
spec:
  packageRef:
    refName: cert-manager.tanzu.vmware.com
    versionSelection:
      constraints: #@ getVersionByPackage("cert-manager")
  serviceAccountName: #@ data.values.service_account_name